// Generated by Wrangler on Fri Aug 30 2024 17:38:17 GMT+0800 (China Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	KV: KVNamespace;
	DB: D1Database;
}
