// Generated by Wrangler on Sun Aug 25 2024 14:52:25 GMT+0800 (China Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	DB: D1Database;
}
